# Generated by Django 4.2.7 on 2025-08-10 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام منبع')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('resource_type', models.CharField(choices=[('dataset', 'مجموعه داده'), ('model', 'مدل'), ('api', 'API'), ('tool', 'ابزار'), ('service', 'سرویس'), ('template', 'قالب')], max_length=20, verbose_name='نوع منبع')),
                ('source_url', models.URLField(blank=True, verbose_name='آدرس منبع')),
                ('local_path', models.CharField(blank=True, max_length=500, verbose_name='مسیر محلی')),
                ('metadata', models.JSONField(default=dict, verbose_name='متادیتا')),
                ('is_offline_available', models.BooleanField(default=False, verbose_name='در دسترس آفلاین')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم فایل')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='نسخه')),
                ('tags', models.JSONField(default=list, verbose_name='برچسب\u200cها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'منبع هوش مصنوعی',
                'verbose_name_plural': 'منابع هوش مصنوعی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سایت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('domain', models.CharField(blank=True, max_length=255, verbose_name='دامنه')),
                ('subdomain', models.CharField(blank=True, max_length=100, verbose_name='زیردامنه')),
                ('html_content', models.TextField(verbose_name='محتوای HTML')),
                ('css_content', models.TextField(blank=True, verbose_name='محتوای CSS')),
                ('js_content', models.TextField(blank=True, verbose_name='محتوای JavaScript')),
                ('assets', models.JSONField(default=dict, verbose_name='فایل\u200cهای ضمیمه')),
                ('settings', models.JSONField(default=dict, verbose_name='تنظیمات')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'آرشیو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('is_public', models.BooleanField(default=False, verbose_name='عمومی')),
                ('seo_settings', models.JSONField(default=dict, verbose_name='تنظیمات SEO')),
                ('analytics_code', models.TextField(blank=True, verbose_name='کد آنالیتیکس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'سایت تولید شده',
                'verbose_name_plural': 'سایت\u200cهای تولید شده',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام قالب')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('html_content', models.TextField(verbose_name='محتوای HTML')),
                ('css_content', models.TextField(blank=True, verbose_name='محتوای CSS')),
                ('js_content', models.TextField(blank=True, verbose_name='محتوای JavaScript')),
                ('preview_image', models.ImageField(blank=True, upload_to='templates/previews/', verbose_name='تصویر پیش\u200cنمایش')),
                ('template_file', models.FileField(blank=True, upload_to='templates/files/', verbose_name='فایل قالب')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('draft', 'پیش\u200cنویس')], default='active', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_free', models.BooleanField(default=True, verbose_name='رایگان')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت')),
                ('tags', models.JSONField(default=list, verbose_name='برچسب\u200cها')),
                ('metadata', models.JSONField(default=dict, verbose_name='متادیتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'قالب سایت',
                'verbose_name_plural': 'قالب\u200cهای سایت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('name_en', models.CharField(max_length=100, verbose_name='نام انگلیسی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('icon', models.CharField(default='fas fa-folder', max_length=50, verbose_name='آیکون')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='رنگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی قالب',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای قالب',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام پروژه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('settings', models.JSONField(default=dict, verbose_name='تنظیمات')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('archived', 'آرشیو شده'), ('deleted', 'حذف شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('sites', models.ManyToManyField(blank=True, to='sitebuilder_app.generatedsite', verbose_name='سایت\u200cها')),
                ('templates', models.ManyToManyField(blank=True, to='sitebuilder_app.sitetemplate', verbose_name='قالب\u200cها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروژه کاربر',
                'verbose_name_plural': 'پروژه\u200cهای کاربر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitetemplate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitebuilder_app.templatecategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='generatedsite',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitebuilder_app.sitetemplate', verbose_name='قالب'),
        ),
        migrations.AddField(
            model_name='generatedsite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.CreateModel(
            name='AIExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=50, verbose_name='نوع وظیفه')),
                ('source_url', models.URLField(blank=True, verbose_name='آدرس منبع')),
                ('source_type', models.CharField(max_length=50, verbose_name='نوع منبع')),
                ('configuration', models.JSONField(default=dict, verbose_name='پیکربندی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('running', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('progress', models.IntegerField(default=0, verbose_name='پیشرفت')),
                ('result_data', models.JSONField(default=dict, verbose_name='داده\u200cهای نتیجه')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'وظیفه استخراج هوش مصنوعی',
                'verbose_name_plural': 'وظایف استخراج هوش مصنوعی',
                'ordering': ['-created_at'],
            },
        ),
    ]
